import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useParams, Link } from "wouter";
import { Printer, ArrowLeft, AlertTriangle, Zap, Lock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/hooks/use-auth";
import { NetWorthUpgradeModal } from "@/components/NetWorthUpgradeModal";
import type { Report, NetWorthStatement, NetWorthItem, IncomeStrategy } from "@shared/schema";

// ── types ─────────────────────────────────────────────────────────────────────

interface NetWorthDetail {
  statement: NetWorthStatement;
  items: NetWorthItem[];
}

interface ReportPayload {
  report: Report;
  detail: NetWorthDetail | IncomeStrategy | null;
  user: { email: string; profile: { firstName?: string; lastName?: string; province?: string } | null };
}

// ── helpers ───────────────────────────────────────────────────────────────────

const $ = (n: number) =>
  new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD", maximumFractionDigits: 0 }).format(n);

const fmtDate = (d: string | Date) =>
  new Date(d).toLocaleDateString("en-CA", { year: "numeric", month: "long", day: "numeric" });

const rptId = (id: number) => `RPT-${String(id).padStart(5, "0")}`;

const PROVINCES: Record<string, string> = {
  ON: "Ontario", BC: "British Columbia", AB: "Alberta", QC: "Quebec",
  SK: "Saskatchewan", MB: "Manitoba", NS: "Nova Scotia", NB: "New Brunswick",
  NL: "Newfoundland & Labrador", PE: "Prince Edward Island",
};

function isNetWorthDetail(d: any): d is NetWorthDetail {
  return d != null && "statement" in d && "items" in d;
}

const GOLD = "#C5A35A";
const NAVY = "#0D1929";

// ── print styles ──────────────────────────────────────────────────────────────

const PRINT_CSS = `
  @media print {
    .no-print { display: none !important; }
    body { background: white !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .doc-page { box-shadow: none !important; border-radius: 0 !important; margin: 0 !important; }
  }
  @page { size: A4; margin: 1.5cm 2cm; }
`;

// ── Document header ───────────────────────────────────────────────────────────

function DocHeader({ payload }: { payload: ReportPayload }) {
  const { report, user } = payload;
  const fullName = [user.profile?.firstName, user.profile?.lastName].filter(Boolean).join(" ");
  const preparedFor = fullName || user.email;

  return (
    <>
      {/* Dark cover bar */}
      <div className="px-10 py-8 flex items-start justify-between"
        style={{ background: NAVY }}>
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-xl" style={{ background: GOLD }}>
            <Zap className="w-5 h-5" style={{ color: NAVY }} />
          </div>
          <span className="text-xl font-bold text-white">adavi.ai</span>
        </div>
        <div className="text-right">
          <p className="text-xs font-mono" style={{ color: "rgba(255,255,255,0.45)" }}>Report ID</p>
          <p className="text-sm font-mono font-bold text-white">{rptId(report.id)}</p>
        </div>
      </div>

      {/* Meta row */}
      <div className="px-10 py-5 border-b border-gray-200 flex items-start justify-between gap-6"
        style={{ background: "#FAFAFA" }}>
        <div>
          <p className="text-xs text-gray-400 uppercase tracking-wide font-semibold mb-0.5">Prepared for</p>
          <p className="text-base font-bold text-gray-900">{preparedFor}</p>
        </div>
        <div className="text-right shrink-0 space-y-0.5">
          <p className="text-xs text-gray-400">Generated by <span className="font-semibold text-gray-600">adavi.ai</span></p>
          <p className="text-xs text-gray-400">{fmtDate(report.createdAt)}</p>
          <p className="text-xs font-mono text-gray-400">{rptId(report.id)}</p>
        </div>
      </div>
    </>
  );
}

// ── Document footer ───────────────────────────────────────────────────────────

function DocFooter({ report, preparedFor }: { report: Report; preparedFor: string }) {
  return (
    <div className="px-10 py-6 border-t border-gray-200 space-y-3"
      style={{ background: "#FAFAFA" }}>
      {/* Meta grid */}
      <div className="grid grid-cols-2 gap-x-6 gap-y-1 text-xs text-gray-500">
        <div><span className="font-semibold text-gray-700">Prepared for:</span> {preparedFor}</div>
        <div><span className="font-semibold text-gray-700">Generated by:</span> adavi.ai (adiva.ai)</div>
        <div><span className="font-semibold text-gray-700">Date:</span> {fmtDate(report.createdAt)}</div>
        <div><span className="font-semibold text-gray-700">Report ID:</span> {rptId(report.id)}</div>
      </div>

      {/* Disclaimer */}
      <div className="flex items-start gap-2 pt-2 border-t border-gray-100">
        <AlertTriangle className="w-3.5 h-3.5 text-amber-500 shrink-0 mt-0.5" />
        <p className="text-xs text-gray-500 leading-relaxed">
          <strong className="text-gray-700">Disclaimer:</strong> This report is for educational purposes only and does not constitute tax, legal, financial, or accounting advice. All figures are estimates based on 2026 Canadian federal and provincial tax rules. Actual results will vary. Always consult a licensed CPA or tax professional before making compensation decisions.
          © {new Date().getFullYear()} Adavi Inc. All rights reserved.
        </p>
      </div>
    </div>
  );
}

// ── Net Worth Report ──────────────────────────────────────────────────────────

function NetWorthReport({ detail }: { detail: NetWorthDetail }) {
  const { statement, items } = detail;
  const assets      = items.filter(i => i.type === "asset");
  const liabilities = items.filter(i => i.type === "liability");
  const isPositive  = statement.netWorth >= 0;

  const uniq = (list: NetWorthItem[]) => [...new Set(list.map(i => i.category))].sort();

  function ItemTable({ list, color }: { list: NetWorthItem[]; color: string }) {
    return (
      <table className="w-full text-sm border-collapse">
        <thead>
          <tr style={{ background: "#F3F4F6" }}>
            <th className="text-left px-3 py-2 border border-gray-200 text-xs font-semibold text-gray-600 uppercase tracking-wide">Name</th>
            <th className="text-left px-3 py-2 border border-gray-200 text-xs font-semibold text-gray-600 uppercase tracking-wide">Category</th>
            <th className="text-right px-3 py-2 border border-gray-200 text-xs font-semibold text-gray-600 uppercase tracking-wide">Amount</th>
          </tr>
        </thead>
        <tbody>
          {uniq(list).map(cat => (
            <>
              <tr key={`cat-${cat}`} style={{ background: "#FAFAFA" }}>
                <td colSpan={3} className="px-3 py-1.5 border border-gray-200">
                  <span className="text-xs font-bold text-gray-400 uppercase tracking-wider">{cat}</span>
                </td>
              </tr>
              {list.filter(i => i.category === cat).map(item => (
                <tr key={item.id}>
                  <td className="px-3 py-2 border border-gray-100 text-gray-800">{item.name}</td>
                  <td className="px-3 py-2 border border-gray-100 text-xs text-gray-500">{item.category}</td>
                  <td className="px-3 py-2 border border-gray-100 text-right font-mono" style={{ color }}>{$(item.amount)}</td>
                </tr>
              ))}
            </>
          ))}
        </tbody>
      </table>
    );
  }

  return (
    <div className="px-10 py-8 space-y-8">
      {/* Title */}
      <div>
        <p className="text-xs font-bold uppercase tracking-widest mb-1" style={{ color: GOLD }}>Net Worth Summary</p>
        <h1 className="text-2xl font-bold text-gray-900">Statement of Net Worth</h1>
        <p className="text-sm text-gray-500">Personal financial position — all figures in CAD</p>
      </div>

      {/* Totals */}
      <div className="grid grid-cols-3 gap-4">
        {[
          { label: "Total Assets",      value: statement.totalAssets,      color: "#16a34a", bg: "#f0fdf4" },
          { label: "Total Liabilities", value: statement.totalLiabilities, color: "#dc2626", bg: "#fef2f2" },
          { label: "Net Worth",         value: statement.netWorth,         color: isPositive ? "#1d4ed8" : "#dc2626", bg: isPositive ? "#eff6ff" : "#fef2f2" },
        ].map(c => (
          <div key={c.label} className="rounded-xl border p-4"
            style={{ borderColor: c.color + "30", background: c.bg }}>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">{c.label}</p>
            <p className="text-xl font-extrabold" style={{ color: c.color }}>{$(c.value)}</p>
          </div>
        ))}
      </div>

      {/* Assets */}
      {assets.length > 0 && (
        <div>
          <h2 className="text-sm font-bold text-gray-700 mb-2 flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-green-500 inline-block" />Assets
          </h2>
          <ItemTable list={assets} color="#16a34a" />
          <div className="flex justify-between px-3 py-2.5 bg-green-50 border border-green-200 rounded-b-lg">
            <span className="text-sm font-bold text-gray-800">Total Assets</span>
            <span className="text-sm font-bold font-mono text-green-700">{$(statement.totalAssets)}</span>
          </div>
        </div>
      )}

      {/* Liabilities */}
      {liabilities.length > 0 && (
        <div>
          <h2 className="text-sm font-bold text-gray-700 mb-2 flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-red-500 inline-block" />Liabilities
          </h2>
          <ItemTable list={liabilities} color="#dc2626" />
          <div className="flex justify-between px-3 py-2.5 bg-red-50 border border-red-200 rounded-b-lg">
            <span className="text-sm font-bold text-gray-800">Total Liabilities</span>
            <span className="text-sm font-bold font-mono text-red-700">{$(statement.totalLiabilities)}</span>
          </div>
        </div>
      )}

      {/* Net worth callout */}
      <div className="rounded-xl border-2 p-5 flex items-center justify-between"
        style={{ borderColor: isPositive ? "#1d4ed8" : "#dc2626", background: isPositive ? "#eff6ff" : "#fef2f2" }}>
        <div>
          <p className="text-sm font-semibold text-gray-600">Net Worth</p>
          <p className="text-xs text-gray-400">Total assets minus total liabilities</p>
        </div>
        <p className="text-3xl font-extrabold" style={{ color: isPositive ? "#1d4ed8" : "#dc2626" }}>
          {$(statement.netWorth)}
        </p>
      </div>

      {items.length === 0 && (
        <div className="rounded-xl border border-dashed border-gray-200 p-8 text-center">
          <p className="text-sm text-gray-400">No items have been recorded in this statement.</p>
        </div>
      )}
    </div>
  );
}

// ── Income Strategy Report ────────────────────────────────────────────────────

function IncomeStrategyReport({ detail }: { detail: IncomeStrategy }) {
  const s = detail;
  const province   = PROVINCES[s.province] ?? s.province;
  const cppRrsp    = s.wantsCppRrsp === "yes" ? "Important — build CPP & RRSP room" : s.wantsCppRrsp === "no" ? "Skip — minimize CPP costs" : "Neutral — not a current priority";
  const simplicity = s.preferSimple ? "Simple (easy 50/50 split)" : "Full tax optimization";
  const salary     = s.salaryRecommendation ?? 0;
  const dividends  = s.dividendRecommendation ?? 0;
  const total      = salary + dividends;
  const salaryPct  = total > 0 ? Math.round((salary / total) * 100) : 50;
  const divPct     = 100 - salaryPct;

  return (
    <div className="px-10 py-8 space-y-8">
      {/* Title */}
      <div>
        <p className="text-xs font-bold uppercase tracking-widest mb-1" style={{ color: GOLD }}>Income Strategy Summary</p>
        <h1 className="text-2xl font-bold text-gray-900">Salary vs. Dividend Analysis</h1>
        <p className="text-sm text-gray-500">Compensation strategy for your Canadian-controlled private corporation (CCPC)</p>
      </div>

      {/* Inputs */}
      <div>
        <h2 className="text-sm font-bold text-gray-500 uppercase tracking-widest mb-3">Analysis Inputs</h2>
        <div className="grid grid-cols-2 gap-3">
          {[
            { label: "Province",                    value: province },
            { label: "Corporate Profit",            value: $(s.corporateProfit) },
            { label: "Desired Cash Withdrawal",     value: s.desiredCashWithdrawal > 0 ? $(s.desiredCashWithdrawal) : "Not specified" },
            { label: "GRIP Balance",                value: s.gripBalance != null ? $(s.gripBalance) : "Not provided" },
            { label: "CPP / RRSP Priority",         value: cppRrsp },
            { label: "Strategy Preference",         value: simplicity },
          ].map(r => (
            <div key={r.label} className="rounded-lg border border-gray-200 bg-gray-50 px-4 py-3">
              <p className="text-xs text-gray-500 font-semibold mb-0.5">{r.label}</p>
              <p className="text-sm font-bold text-gray-800">{r.value}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Recommended strategy — gold card */}
      <div>
        <h2 className="text-sm font-bold text-gray-500 uppercase tracking-widest mb-3">Recommended Compensation Strategy</h2>
        <div className="rounded-xl border-2 p-6" style={{ borderColor: GOLD, background: "#FFFBF0" }}>
          <div className="flex items-center gap-2 mb-5">
            <div className="w-2.5 h-2.5 rounded-full" style={{ background: GOLD }} />
            <p className="text-sm font-bold text-gray-800">Optimal Salary / Dividend Split</p>
          </div>

          {/* Visual split bar */}
          <div className="mb-5">
            <div className="flex rounded-full overflow-hidden h-5 mb-2 border border-gray-200">
              <div style={{ width: `${salaryPct}%`, background: "#1d4ed8" }}
                className="flex items-center justify-center">
                {salaryPct >= 20 && <span className="text-xs text-white font-bold">{salaryPct}%</span>}
              </div>
              <div style={{ width: `${divPct}%`, background: "#16a34a" }}
                className="flex items-center justify-center">
                {divPct >= 20 && <span className="text-xs text-white font-bold">{divPct}%</span>}
              </div>
            </div>
            <div className="flex justify-between text-xs text-gray-500">
              <span className="flex items-center gap-1">
                <span className="w-2 h-2 rounded-full inline-block" style={{ background: "#1d4ed8" }} />
                Salary
              </span>
              <span className="flex items-center gap-1">
                Dividends
                <span className="w-2 h-2 rounded-full inline-block" style={{ background: "#16a34a" }} />
              </span>
            </div>
          </div>

          {/* Amounts */}
          <div className="grid grid-cols-3 gap-4 pt-4 border-t border-yellow-200">
            {[
              { label: "Annual Salary",    value: $(salary),    color: "#1d4ed8" },
              { label: "Annual Dividends", value: $(dividends), color: "#16a34a" },
              { label: "Total Withdrawal", value: $(total),     color: NAVY },
            ].map(c => (
              <div key={c.label} className="text-center">
                <p className="text-xs text-gray-500 mb-1">{c.label}</p>
                <p className="text-xl font-extrabold" style={{ color: c.color }}>{c.value}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Rationale */}
      {s.blendedNote && (
        <div>
          <h2 className="text-sm font-bold text-gray-500 uppercase tracking-widest mb-3">Strategy Rationale</h2>
          <div className="rounded-xl border border-gray-200 bg-gray-50 p-5">
            <p className="text-sm text-gray-700 leading-relaxed">{s.blendedNote}</p>
          </div>
        </div>
      )}

      {/* Key considerations */}
      <div>
        <h2 className="text-sm font-bold text-gray-500 uppercase tracking-widest mb-3">Key Considerations</h2>
        <div className="space-y-2">
          {[
            `Analysis uses 2026 Canadian federal + ${province} provincial income tax brackets.`,
            "Dividend figures assume non-eligible dividends (typical for CCPCs with the small business deduction).",
            "CPP contributions are based on the salary portion only. 2026 maximum pensionable earnings: $68,500.",
            "RRSP contribution room is generated only on employment income — dividends do not create RRSP room.",
            s.gripBalance != null
              ? `A GRIP balance of ${$(s.gripBalance)} was provided. Confirm eligible dividend eligibility with your accountant.`
              : "No GRIP balance was provided. Analysis assumes non-eligible dividends only.",
          ].map((point, i) => (
            <div key={i} className="flex items-start gap-2.5 text-sm text-gray-600">
              <span className="shrink-0 w-5 h-5 rounded-full text-xs flex items-center justify-center font-bold mt-0.5"
                style={{ background: GOLD + "20", color: GOLD }}>
                {i + 1}
              </span>
              {point}
            </div>
          ))}
        </div>
      </div>

      {/* Accountant callout */}
      <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 flex items-start gap-3">
        <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
        <div>
          <p className="text-sm font-semibold text-amber-800">Review with your accountant before implementing</p>
          <p className="text-xs text-amber-700 mt-0.5 leading-relaxed">
            Your actual optimal mix depends on marginal tax rates, retained earnings, shareholder loans, your spouse's income, and other factors. Share this report with your CPA as a starting point for your year-end compensation planning conversation.
          </p>
        </div>
      </div>
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function PDFReportPreview() {
  const { id } = useParams<{ id: string }>();
  const reportNum = parseInt(id ?? "0");
  const { user } = useAuth();
  const isPro = user?.subscriptionStatus === "active" || user?.subscriptionStatus === "trialing";
  const [showUpgradeModal, setShowUpgradeModal] = useState(false);

  const { data, isLoading, isError } = useQuery<ReportPayload>({
    queryKey: ["/api/reports", reportNum],
    queryFn: async () => {
      const res = await fetch(`/api/reports/${reportNum}`, { credentials: "include" });
      if (!res.ok) throw new Error("Not found");
      return res.json();
    },
    enabled: !isNaN(reportNum) && reportNum > 0,
    retry: false,
  });

  const preparedFor = data
    ? [data.user.profile?.firstName, data.user.profile?.lastName].filter(Boolean).join(" ") || data.user.email
    : "";

  return (
    <>
      <style>{PRINT_CSS}</style>
      <NetWorthUpgradeModal open={showUpgradeModal} onClose={() => setShowUpgradeModal(false)} />

      {/* Toolbar — screen only */}
      <div className="no-print sticky top-0 z-10 bg-white border-b border-gray-200 shadow-sm px-6 py-3 flex items-center justify-between">
        <Link href="/reports">
          <Button variant="ghost" size="sm" className="gap-1.5 text-gray-600 hover:text-gray-900"
            data-testid="button-back-reports">
            <ArrowLeft className="w-4 h-4" />Back to Reports
          </Button>
        </Link>
        <div className="flex items-center gap-3">
          {data && (
            <span className="text-xs font-mono text-gray-400 hidden sm:inline">
              {rptId(data.report.id)} · {fmtDate(data.report.createdAt)}
            </span>
          )}
          {isPro ? (
            <Button size="sm" onClick={() => window.print()}
              className="gap-1.5 font-semibold"
              style={{ background: GOLD, color: "white" }}
              data-testid="button-print-pdf">
              <Printer className="w-4 h-4" />Print / Save PDF
            </Button>
          ) : (
            <Button size="sm" onClick={() => setShowUpgradeModal(true)}
              className="gap-1.5 font-semibold"
              style={{ background: "rgba(197,163,90,0.12)", color: GOLD, border: `1px solid rgba(197,163,90,0.3)` }}
              data-testid="button-upgrade-pdf">
              <Lock className="w-4 h-4" />Download PDF — Pro
            </Button>
          )}
        </div>
      </div>

      {/* Document */}
      <div className="min-h-screen py-8 px-4" style={{ background: "#E5E7EB" }}>
        <div className="doc-page bg-white rounded-2xl shadow-xl mx-auto overflow-hidden"
          style={{ maxWidth: "820px", minHeight: "1100px" }}>

          {/* Loading */}
          {isLoading && (
            <div className="p-10 space-y-4 animate-pulse">
              <div className="h-8 bg-gray-200 rounded w-40" />
              <div className="h-4 bg-gray-100 rounded w-full" />
              <div className="h-4 bg-gray-100 rounded w-3/4" />
              <div className="h-32 bg-gray-100 rounded" />
            </div>
          )}

          {/* Error */}
          {isError && (
            <div className="flex flex-col items-center gap-4 py-24 text-center px-10">
              <AlertTriangle className="w-12 h-12 text-amber-400" />
              <h2 className="text-xl font-bold text-gray-800">Report not found</h2>
              <p className="text-sm text-gray-500 max-w-xs">This report may have been deleted or you may not have access to it.</p>
              <Link href="/reports">
                <Button className="mt-2 font-bold" style={{ background: GOLD, color: "white" }}>
                  Back to Reports
                </Button>
              </Link>
            </div>
          )}

          {/* Content */}
          {data && (
            <>
              <DocHeader payload={data} />

              {data.report.reportType === "net_worth" && isNetWorthDetail(data.detail) && (
                <NetWorthReport detail={data.detail} />
              )}

              {data.report.reportType === "income_strategy" && data.detail && !isNetWorthDetail(data.detail) && (
                <IncomeStrategyReport detail={data.detail as IncomeStrategy} />
              )}

              {!data.detail && (
                <div className="px-10 py-16 text-center">
                  <p className="text-sm text-gray-400">Report detail data is not available.</p>
                </div>
              )}

              <DocFooter report={data.report} preparedFor={preparedFor} />
            </>
          )}
        </div>
      </div>
    </>
  );
}
